networks:
  backend:

services:
  cosmosnosqlapi:
    image: ${DOCKER_REGISTRY-}cosmosnosqlapidemo
    container_name: cosmos-nosql-api
    networks:
      - backend
    build:
      context: .
      dockerfile: CosmosDb.NoSql.API/Dockerfile
    ports:
      - 5199:80
    # depends_on:
    #   - cosmosnosql
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - CosmosEndpointUri=https://localhost:8081
      - CosmosPrimaryKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==